//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 10:15:54 PM PDT 
//


package com.sellaspot.datamodel;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="itemid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bidid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "", propOrder = {
//    "itemid",
//    "bidid"
//})
@Root(name = "AcceptBidRequest", strict = false)
public class AcceptBidRequest {

	@Element(required = false)
    protected int itemid;
	@Element(required = false)
	protected int bidid;

    /**
     * Gets the value of the itemid property.
     * 
     */
    public int getItemid() {
        return itemid;
    }

    /**
     * Sets the value of the itemid property.
     * 
     */
    public void setItemid(int value) {
        this.itemid = value;
    }

    /**
     * Gets the value of the bidid property.
     * 
     */
    public int getBidid() {
        return bidid;
    }

    /**
     * Sets the value of the bidid property.
     * 
     */
    public void setBidid(int value) {
        this.bidid = value;
    }

}
