//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 10:53:03 PM PDT 
//


package com.sellaspot.datamodel;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="itemid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="userid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="venuename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itemdescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datetimeforitem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="expired" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bidid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userdescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itemusertype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="notified" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "", propOrder = {
//    "itemid",
//    "userid",
//    "venuename",
//    "address",
//    "city",
//    "state",
//    "itemdescription",
//    "country",
//    "category",
//    "datetimeforitem",
//    "price",
//    "expired",
//    "quantity",
//    "bidid",
//    "timestamp",
//    "userdescription",
//    "itemusertype",
//    "notified"
//})
@Root(name = "SpotDetail")
public class SpotDetail {

    protected int itemid;
    protected int userid;
    @Element(required = true)
    protected String venuename;
    @Element(required = true)
    protected String address;
    @Element(required = true)
    protected String city;
    @Element(required = true)
    protected String state;
    @Element(required = true)
    protected String itemdescription;
    @Element(required = true)
    protected String country;
    @Element(required = true)
    protected String category;
    @Element(required = true)
    protected String datetimeforitem;
    protected int price;
    @Element(required = true)
    protected String expired;
    protected int quantity;
    protected int bidid;
    @Element(required = true)
    protected String timestamp;
    @Element(required = true)
    protected String userdescription;
    @Element(required = true)
    protected String itemusertype;
    @Element(required = true)
    protected String notified;

    /**
     * Gets the value of the itemid property.
     * 
     */
    public int getItemid() {
        return itemid;
    }

    /**
     * Sets the value of the itemid property.
     * 
     */
    public void setItemid(int value) {
        this.itemid = value;
    }

    /**
     * Gets the value of the userid property.
     * 
     */
    public int getUserid() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     */
    public void setUserid(int value) {
        this.userid = value;
    }

    /**
     * Gets the value of the venuename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVenuename() {
        return venuename;
    }

    /**
     * Sets the value of the venuename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVenuename(String value) {
        this.venuename = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the itemdescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemdescription() {
        return itemdescription;
    }

    /**
     * Sets the value of the itemdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemdescription(String value) {
        this.itemdescription = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the datetimeforitem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatetimeforitem() {
        return datetimeforitem;
    }

    /**
     * Sets the value of the datetimeforitem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatetimeforitem(String value) {
        this.datetimeforitem = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    public int getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    public void setPrice(int value) {
        this.price = value;
    }

    /**
     * Gets the value of the expired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpired() {
        return expired;
    }

    /**
     * Sets the value of the expired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpired(String value) {
        this.expired = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(int value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the bidid property.
     * 
     */
    public int getBidid() {
        return bidid;
    }

    /**
     * Sets the value of the bidid property.
     * 
     */
    public void setBidid(int value) {
        this.bidid = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimestamp(String value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the userdescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserdescription() {
        return userdescription;
    }

    /**
     * Sets the value of the userdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserdescription(String value) {
        this.userdescription = value;
    }

    /**
     * Gets the value of the itemusertype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemusertype() {
        return itemusertype;
    }

    /**
     * Sets the value of the itemusertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemusertype(String value) {
        this.itemusertype = value;
    }

    /**
     * Gets the value of the notified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotified() {
        return notified;
    }

    /**
     * Sets the value of the notified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotified(String value) {
        this.notified = value;
    }

}
