//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.10 at 06:56:19 PM PDT 
//


package com.sellaspot.datamodel;

import java.util.ArrayList;
import java.util.List;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Root;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalrating" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ratedspot" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="raterid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="itemid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="rating" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="ratingtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "", propOrder = {
//    "firstname",
//    "totalrating",
//    "status",
//    "reason",
//    "ratedspot"
//})
@Root(name = "UserRating", strict = false)
public class UserRating {

    @Element(required = false)
    protected String firstname;
    @Element(required = false)
    protected float totalrating;
    @Element(required = false)
    protected String status;
    @Element(required = false)
    protected String reason;
	@ElementList(inline = true)
    protected List<UserRating.Ratedspot> ratedspot;

    /**
     * Gets the value of the firstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstname(String value) {
        this.firstname = value;
    }

    /**
     * Gets the value of the totalrating property.
     * 
     */
    public float getTotalrating() {
        return totalrating;
    }

    /**
     * Sets the value of the totalrating property.
     * 
     */
    public void setTotalrating(float value) {
        this.totalrating = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the ratedspot property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ratedspot property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRatedspot().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserRating.Ratedspot }
     * 
     * 
     */
    public List<UserRating.Ratedspot> getRatedspot() {
        if (ratedspot == null) {
            ratedspot = new ArrayList<UserRating.Ratedspot>();
        }
        return this.ratedspot;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="raterid" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="itemid" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="rating" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ratingtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
//    @XmlAccessorType(XmlAccessType.FIELD)
//    @XmlType(name = "", propOrder = {
//        "raterid",
//        "itemid",
//        "rating",
//        "ratingtype",
//        "comments"
//    })
	@Element(required = false)
    public static class Ratedspot {

        @Element(required = false)
        protected int raterid;
        @Element(required = false)
        protected int itemid;
        @Element(required = false)
        protected int rating;
        @Element(required = false)
        protected String ratingtype;
        @Element(required = false)
        protected String comments;

        /**
         * Gets the value of the raterid property.
         * 
         */
        public int getRaterid() {
            return raterid;
        }

        /**
         * Sets the value of the raterid property.
         * 
         */
        public void setRaterid(int value) {
            this.raterid = value;
        }

        /**
         * Gets the value of the itemid property.
         * 
         */
        public int getItemid() {
            return itemid;
        }

        /**
         * Sets the value of the itemid property.
         * 
         */
        public void setItemid(int value) {
            this.itemid = value;
        }

        /**
         * Gets the value of the rating property.
         * 
         */
        public int getRating() {
            return rating;
        }

        /**
         * Sets the value of the rating property.
         * 
         */
        public void setRating(int value) {
            this.rating = value;
        }

        /**
         * Gets the value of the ratingtype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRatingtype() {
            return ratingtype;
        }

        /**
         * Sets the value of the ratingtype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRatingtype(String value) {
            this.ratingtype = value;
        }

        /**
         * Gets the value of the comments property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComments() {
            return comments;
        }

        /**
         * Sets the value of the comments property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComments(String value) {
            this.comments = value;
        }

    }

}
