//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.31 at 09:37:59 PM PDT 
//


package com.sellaspot.datamodel;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="itemid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="userid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bidprice" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="userdescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bidusertype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "", propOrder = {
//    "itemid",
//    "userid",
//    "bidprice",
//    "userdescription",
//    "bidusertype"
//})
@Root(name = "BidRequest")
public class BidRequest {

    @Element(required = true)
    protected int itemid;
    @Element(required = true)
    protected int userid;
    @Element(required = true)
    protected int bidprice;
    @Element(required = true)
    protected String userdescription;
    @Element(required = true)
    protected String bidusertype;

    /**
     * Gets the value of the itemid property.
     * 
     */
    public int getItemid() {
        return itemid;
    }

    /**
     * Sets the value of the itemid property.
     * 
     */
    public void setItemid(int value) {
        this.itemid = value;
    }

    /**
     * Gets the value of the userid property.
     * 
     */
    public int getUserid() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     */
    public void setUserid(int value) {
        this.userid = value;
    }

    /**
     * Gets the value of the bidprice property.
     * 
     */
    public int getBidprice() {
        return bidprice;
    }

    /**
     * Sets the value of the bidprice property.
     * 
     */
    public void setBidprice(int value) {
        this.bidprice = value;
    }

    /**
     * Gets the value of the userdescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserdescription() {
        return userdescription;
    }

    /**
     * Sets the value of the userdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserdescription(String value) {
        this.userdescription = value;
    }

    /**
     * Gets the value of the bidusertype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBidusertype() {
        return bidusertype;
    }

    /**
     * Sets the value of the bidusertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBidusertype(String value) {
        this.bidusertype = value;
    }

}
