//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.31 at 09:37:59 PM PDT 
//


package com.sellaspot.datamodel;



/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.spotmob.rest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
//@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.spotmob.rest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BuyASpotRequest }
     * 
     */
    public BuyASpotRequest createBuyASpotRequest() {
        return new BuyASpotRequest();
    }

    /**
     * Create an instance of {@link RegisterResponse }
     * 
     */
    public RegisterResponse createRegisterResponse() {
        return new RegisterResponse();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link RegisterUser }
     * 
     */
    public RegisterUser createRegisterUser() {
        return new RegisterUser();
    }

    /**
     * Create an instance of {@link BidResponse }
     * 
     */
    public BidResponse createBidResponse() {
        return new BidResponse();
    }

    /**
     * Create an instance of {@link BidRequest }
     * 
     */
    public BidRequest createBidRequest() {
        return new BidRequest();
    }

    /**
     * Create an instance of {@link SpotDetail }
     * 
     */
    public SpotDetail createSpotDetail() {
        return new SpotDetail();
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
//    public NewDataSet createNewDataSet() {
//        return new NewDataSet();
//    }

    /**
     * Create an instance of {@link BuyASpotResponse }
     * 
     */
    public BuyASpotResponse createBuyASpotResponse() {
        return new BuyASpotResponse();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }
    
    /**
     * Create an instance of {@link AcceptBidResponse }
     * 
     */
    public AcceptBidResponse createAcceptBidResponse() {
        return new AcceptBidResponse();
    }

    /**
     * Create an instance of {@link AcceptBidRequest }
     * 
     */
    public AcceptBidRequest createAcceptBidRequest() {
        return new AcceptBidRequest();
    }

}
