//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.10 at 06:56:19 PM PDT 
//


package com.sellaspot.datamodel;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rateduserid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="rateditemid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="raterusertype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rating" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "", propOrder = {
//    "rateduserid",
//    "rateditemid",
//    "raterusertype",
//    "comments",
//    "rating"
//})
@Root(name = "RateUserRequest", strict = false)
public class RateUserRequest {

	@Element(required = false)
    protected int rateduserid;
	@Element(required = false)
    protected int rateditemid;
    @Element(required = false)
    protected String raterusertype;
    @Element(required = false)
    protected String comments;
    @Element(required = false)
    protected int rating;

    /**
     * Gets the value of the rateduserid property.
     * 
     */
    public int getRateduserid() {
        return rateduserid;
    }

    /**
     * Sets the value of the rateduserid property.
     * 
     */
    public void setRateduserid(int value) {
        this.rateduserid = value;
    }

    /**
     * Gets the value of the rateditemid property.
     * 
     */
    public int getRateditemid() {
        return rateditemid;
    }

    /**
     * Sets the value of the rateditemid property.
     * 
     */
    public void setRateditemid(int value) {
        this.rateditemid = value;
    }

    /**
     * Gets the value of the raterusertype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRaterusertype() {
        return raterusertype;
    }

    /**
     * Sets the value of the raterusertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRaterusertype(String value) {
        this.raterusertype = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     */
    public int getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     */
    public void setRating(int value) {
        this.rating = value;
    }

}
